import { type NextRequest, NextResponse } from "next/server"
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/app/api/auth/[...nextauth]/route"
import { db } from "@/lib/db"
import jsPDF from "jspdf"

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session || !session.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await request.json()
    const { alertId, incidentDescription, assignedOfficer } = body

    if (!alertId) {
      return NextResponse.json({ error: "Alert ID is required" }, { status: 400 })
    }

    // Fetch alert from database
    const alert = await db.emergencyAlert.findUnique({
      where: { id: alertId }
    })

    if (!alert) {
      return NextResponse.json({ error: "Alert not found" }, { status: 404 })
    }

    // Fetch complainant details from User profile
    const complainantUser = await db.user.findUnique({
      where: { id: alert.userId }
    })

    const complainantDetails = {
      name: complainantUser?.name || alert.userName || "Unknown Tourist",
      email: complainantUser?.email || "N/A",
      phone: complainantUser?.phone || "N/A",
      alert_type: alert.type,
      severity: alert.severity,
    }

    const firNumber = `E-FIR-${new Date().getFullYear()}-${Math.floor(100000 + Math.random() * 900000)}`

    // Create the E-FIR record
    const efir = await db.efirRecord.create({
      data: {
        alertId: alert.id,
        firNumber,
        incidentDetails: incidentDescription || "No description provided",
        assignedOfficer: assignedOfficer || null,
        complainantDetails: complainantDetails
      }
    })

    // Prepare complete data for PDF generation
    const assignedOfficerUser = assignedOfficer 
      ? await db.user.findUnique({ where: { id: assignedOfficer } })
      : null

    const efirData = {
      fir_number: efir.firNumber,
      created_at: efir.createdAt.toISOString(),
      complainant_details: complainantDetails,
      incident_details: efir.incidentDetails,
      location: alert.locationLat && alert.locationLng ? { lat: alert.locationLat, lng: alert.locationLng } : null,
      assigned_officer_profile: assignedOfficerUser ? {
        full_name: assignedOfficerUser.name,
        email: assignedOfficerUser.email
      } : null
    }

    // Generate PDF
    const pdfBuffer = await generateEFIRPDF(efirData)

    return NextResponse.json({
      firId: efir.id,
      firNumber: efir.firNumber,
      pdfUrl: `data:application/pdf;base64,${pdfBuffer.toString("base64")}`,
      message: "E-FIR generated successfully",
    })
  } catch (error) {
    console.error("E-FIR generation error:", error)
    return NextResponse.json({ error: "Internal server error" }, { status: 500 })
  }
}

async function generateEFIRPDF(efirData: any): Promise<Buffer> {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.text("ELECTRONIC FIRST INFORMATION REPORT (E-FIR)", 20, 30)

  doc.setFontSize(12)
  doc.text(`FIR Number: ${efirData.fir_number}`, 20, 50)
  doc.text(`Date: ${new Date(efirData.created_at).toLocaleDateString()}`, 20, 60)
  doc.text(`Time: ${new Date(efirData.created_at).toLocaleTimeString()}`, 20, 70)

  // Complainant Details
  doc.setFontSize(14)
  doc.text("COMPLAINANT DETAILS:", 20, 90)
  doc.setFontSize(12)

  const complainant = efirData.complainant_details
  doc.text(`Name: ${complainant.name || "N/A"}`, 20, 105)
  doc.text(`Email: ${complainant.email || "N/A"}`, 20, 115)
  doc.text(`Phone: ${complainant.phone || "N/A"}`, 20, 125)

  // Incident Details
  doc.setFontSize(14)
  doc.text("INCIDENT DETAILS:", 20, 145)
  doc.setFontSize(12)

  doc.text(`Alert Type: ${complainant.alert_type || "N/A"}`, 20, 160)
  doc.text(`Severity: ${complainant.severity || "N/A"}`, 20, 170)

  // Incident Description
  const description = efirData.incident_details || "No description provided"
  const splitDescription = doc.splitTextToSize(description, 170)
  doc.text("Description:", 20, 185)
  doc.text(splitDescription, 20, 195)

  // Location
  if (efirData.location) {
    doc.text("Location: Coordinates available in system", 20, 220)
  }

  // Assigned Officer
  if (efirData.assigned_officer_profile) {
    doc.setFontSize(14)
    doc.text("ASSIGNED OFFICER:", 20, 240)
    doc.setFontSize(12)
    doc.text(`Name: ${efirData.assigned_officer_profile.full_name || "N/A"}`, 20, 255)
    doc.text(`Email: ${efirData.assigned_officer_profile.email || "N/A"}`, 20, 265)
  }

  // Footer
  doc.setFontSize(10)
  doc.text("This is a computer-generated document. No signature required.", 20, 280)
  doc.text("Generated by Tourist Safety Monitoring System", 20, 290)

  return Buffer.from(doc.output("arraybuffer"))
}
